= Asciidoctor TeX
Nicolas Wanner
2021-06-23

:adt: Asciidoctor-Tex
:adoc: AsciiDoc

== Introduction

{adt} is an extension which allows to produce a LaTeX file from a document written with the markup language {adoc}.

This project is a fork of Asciidoctor-Latex, with different goals. The idea is to provide the most complete conversion of the {adoc} syntax as possible. But does not offer an extension of the syntax.

Some elements of the syntax are not suitable for the production of printable material and are therefore not implemented or partially implemented.

Render as LaTeX:: Use `asciidoctor-tex foo.adoc` to produce `foo.tex`,
then use `xelatex foo.tex` to create `foo.pdf`.

Quick installation from sources : 

[source, bash]
----
$ cd asciidoctor-tex
$ gem build asciidoctor-tex.gemspec
$ gem install *.gem
----




== Features

* Document styles
  ** articles
  ** books
  ** beamer

* Admonitions

* images
  ** inline
  ** bloc

* table
  ** Column and row span 
  ** Grid and frame lines
  ** Some formatting in cells

* Source code highlighting
  ** LstListing
  ** Pygments

* Custom templates

* Custom environement

== Installation

//=== From Rubygems

//Run `gem install asciidoctor-latex --pre` to install from https://rubygems.org/gems/asciidoctor-latex[RubyGems.org].

//See the https://github.com/asciidoctor/asciidoctor-latex/blob/master/CHANGELOG.adoc[change log] for a list of updates.

//=== From GitHub

//If you would like to install a development version from the repository, use:

// $ git clone https://github.com/asciidoctor/asciidoctor-latex.git
// $ cd asciidoctor-latex
// $ gem build asciidoctor-latex.gemspec
// $ gem install *.gem


==  Contributing

If you wish to contribute to the
https://github.com/asciidoctor/asciidoctor-latex[asciidoctor-latex project], you should set up your environments to use
Jakub Jirutka's https://github.com/asciidoctor/asciidoctor-doctest[asciidoctor-doctest].  At the moment you will need to
use the https://github.com/jxxcarlson/asciidoctor-doctest[version which handles dialects] using
```
gem 'asciidoctor-doctest', github: 'jxxcarlson/asciidoctor-doctest', ref: 'latex'
```
in your Gemfile.  Run all tests with `rake doctest`,
or run individual tests with `rake doctest:html` or
`rake doctest:tex`.

At the moment the tests are for the latex dialect.

== Macros

Macros can be included in the body of an AsciiDoc-LaTeX file using the `texmacro` environment, as in the example below.

----

[env.texmacro]
--
\def\AA{\mathbb{A}}
\def\BB{\mathbb{B}}

\newcommand{\set}[1]{ \{\,#1\,  \} }
\newcommand{\sett}[2]{ \{\,#1\, \mid\, #2\, \} }
--
----

To include a LaTeX macro file MACRO_FILE, insert the code
`include_latex_macros::MACRO_FILE[]`.  Here MACRO_FILE can be a file name or a an absolute or relative path.  Included macros work
for both the html and tex backends.


NOTE: Automatic inclusion of the file `macros.tex`
has been discontinued.


== Switches

.Tex header
To generate a tex file with a minimal header, do:

 $ asciidoctor-latex -a header=no foo.adoc

.Print style
An alternate css file, `data/print.css` is provided
for printing.  It features wider margins and a smaller
type size.  Copy it to the root of your document
folder and use the command `asciidoctor-latex -a stylesheet=print.css`
or more generally `asciidoctor-latex -a stylesheet=path_to/print.css`.


{adlp}'s default form at is `:latexmath`.
To use `:stem`, put the text `:stem:`
in your file.  To turn the switch
on and set it to `latexmath`, say
instead of `stem:latexmth`.



== Document format

Asciidoctor supports two closely-related math formats, [blue]#AsciiDoc-LaTeX# and [blue]#AsciiMath#.

In AsciiDoc-LaTeX, one can write `\$ a^2 + b^2 = c^2 \$` and
----
 \[
    e^{2\pi \sqrt{-1}} = 1,
 \]
----
for in-line and display mathematial
text, respectively.
You will need to express dollar-denominated
currency using
escaped dollar signs, as
 in the sentence, "He paid \$100 for that
theorem."  In AsciiMath, one writes
`+++stem:[ a^2 + b^2 = c^2 ]+++`
and
----
  [stem]
  ++++
    e^{2\pi \sqrt{-1}} = 1.
  ++++
----

